# 📐 從線性概念到最小平方法參數推導全紀錄

本篇筆記將系統化梳理**線性與非線性**的本質區別，並探討如何利用**最小平方法 (Method of Least Squares)** 求解線性方程式中的最佳參數（權重 $w$ 與偏差 $b$）。

---

## 一、 線性 (Linear) 與 非線性 (Non-linear) 的核心區別

在數學與工程領域中，兩者最本質的差異在於**輸入與輸出之間是否成固定比例的直線關係**。

| 特性 | 線性 (Linear) | 非線性 (Non-linear) |
| :--- | :--- | :--- |
| **幾何圖形** | 一條**直線**或平面 | 曲線、拋物線或不規則形狀 |
| **變化規律** | **按比例**均勻變化 | 不按比例，會加速、減速或突變 |
| **疊加原理** | **有效**（整體等於部分之和） | **失效**（整體不等於部分之和） |
| **數學模型** | $y = wx + b$ | $y = wx^2$, $y = \sin(x)$, $y = e^x$ |

### 🛠 跨領域應用對比
*   **機器學習：** 線性回歸（處理線性分類） vs. 深度神經網絡（透過激活函數引入非線性，處理複雜影像與語言）。
*   **工程模擬 (CAE)：** 材料均勻變形的彈性分析（線性） vs. 金屬碰撞、橡膠大變形的塑性分析（非線性）。
*   **影像剪輯：** 傳統磁帶必須依序錄製（線性） vs. 電腦剪輯軟體可任意跳躍段落修改（非線性）。

---

## 二、 最小平方法的核心邏輯

**最小平方法** 是一種在數據中**尋找最佳擬合曲線**的優化技術。

### 1. 為什麼叫「最小平方」？
*   **誤差 (Residual)：** 實際數據點的 $y_i$ 值，與擬合線上對應的 $\hat{y}_i$ 值之間的距離為 $(y_i - \hat{y}_i)$。
*   **為什麼要「平方」？**
    1. 數據點分散在直線上下，直接相加會正負抵消。
    2. 平方可以消除正負號，且在微積分中比絕對值更容易求導。
    3. **平方會放大較大的誤差**，迫使模型去修正遠離群體的極端異常點。

### 2. 線性與非線性的求解差異
*   **線性最小平方：** 尋找一條直線。擁有標準的**解析解 (Closed-form solution)**，可透過公式或矩陣運算直接算出精確值。
*   **非線性最小平方：** 數據呈曲線（如物種增長）。**沒有直接的公式解**，必須依賴電腦進行多次**迭代優化算法**（如高斯-牛頓法、LM 算法）逐步逼近。

---

## 三、 線性方程式的參數權重與偏差推導

以下利用微積分偏微分法，推導線性方程式 $\hat{y} = w x + b$ 中**權重 $w$ (斜率)** 與 **偏差 $b$ (截距)** 的最佳解。

### 1. 定義損失函數 (Loss Function)
假設我們有 $n$ 個觀測數據點 $(x_1, y_1), (x_2, y_2), \dots, (x_n, y_n)$。我們將誤差平方和定義為損失函數 $E(w, b)$：

$$E(w, b) = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \sum_{i=1}^{n} \left[ y_i - (wx_i + b) \right]^2$$

> 📌 **優化目標：** 尋找一組 $(w, b)$ 使得 $E(w, b)$ 最小。多元函數的極值出現在**偏導數皆為 0** 的地方。

---

### 2. 求解偏差 b
將損失函數 $E$ 對偏差 $b$ 求偏導，並令其等於 0：

$$\frac{\partial E}{\partial b} = \sum_{i=1}^{n} 2\left[ y_i - (wx_i + b) \right] \cdot (-1) = 0$$

消去常數 -2，並將連加號 $\sum$ 展開：

$$\sum_{i=1}^{n} y_i - w\sum_{i=1}^{n} x_i - \sum_{i=1}^{n} b = 0$$

由於 $\sum_{i=1}^{n} b = nb$，上式可寫為：

$$\sum_{i=1}^{n} y_i - w\sum_{i=1}^{n} x_i - nb = 0$$

將上式兩邊同時除以 $n$：

$$\frac{1}{n}\sum_{i=1}^{n} y_i - w\left(\frac{1}{n}\sum_{i=1}^{n} x_i\right) - b = 0$$

定義樣本平均數 $\bar{y} = \frac{1}{n}\sum y_i$ 與 $\bar{x} = \frac{1}{n}\sum x_i$，移項即可得到 **b 的解析解**：

$$\boxed{b = \bar{y} - w\bar{x}}$$

> 💡 **幾何意義：** 最佳擬合直線必定會通過所有數據點的平均中心點 $(\bar{x}, \bar{y})$。

---

### 3. 求解權重 w
將損失函數 $E$ 對權重 $w$ 求偏導，並令其等於 0：

$$\frac{\partial E}{\partial w} = \sum_{i=1}^{n} 2\left[ y_i - (wx_i + b) \right] \cdot (-x_i) = 0$$

消去常數 -2，並將 $x_i$ 乘入括號中：

$$\sum_{i=1}^{n} (x_i y_i - w x_i^2 - b x_i) = 0$$

將步驟 2 求得的 $b = \bar{y} - w\bar{x}$ 代入上式中：

$$\sum_{i=1}^{n} \left[ x_i y_i - w x_i^2 - (\bar{y} - w\bar{x})x_i \right] = 0$$

展開並將含有 $w$ 的項與不含 $w$ 的項移項分組：

$$\sum_{i=1}^{n} x_i y_i - \bar{y}\sum_{i=1}^{n} x_i = w \left( \sum_{i=1}^{n} x_i^2 - \bar{x}\sum_{i=1}^{n} x_i \right)$$

利用 $\sum_{i=1}^{n} x_i = n\bar{x}$ 進行平均數代換：

$$\sum_{i=1}^{n} x_i y_i - n\bar{x}\bar{y} = w \left( \sum_{i=1}^{n} x_i^2 - n\bar{x}^2 \right)$$

最終移項解出 **w 的解析解**：

$$w = \frac{\sum_{i=1}^{n} x_i y_i - n\bar{x}\bar{y}}{\sum_{i=1}^{n} x_i^2 - n\bar{x}^2}$$

---

### 4. 統計學常用等價變形
利用代數恆等式（將各點減去平均值），可以將 $w$ 的公式改寫為統計學上的**離差平方和（協方差與方差）**形式：

$$\boxed{w = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}}$$

---

## 四.. 🚀 最終公式總結

$$\begin{cases}  w = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2} & \text{(權重 / 斜率)} \\  b = \bar{y} - w\bar{x} & \text{(偏差 / 截距)}  \end{cases}$$


# 🧮 最小平方法分母與分子的代數恆等式推導

我們要證明原始公式如何等價變換為離差形式：
$$原始公式：w = \frac{\sum_{i=1}^{n} x_i y_i - n\bar{x}\bar{y}}{\sum_{i=1}^{n} x_i^2 - n\bar{x}^2} \quad \Longleftrightarrow \quad 離差形式：w = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}$$

在推導開始前，我們必須先掌握**三個連加號（$\sum$）的核心性質**（其中 $\bar{x}, \bar{y}$ 對於索引 $i$ 來說皆為常數）：
1. $\sum_{i=1}^{n} \bar{x} = n\bar{x}$
2. $\sum_{i=1}^{n} x_i = n\bar{x}$
3. $\sum_{i=1}^{n} \bar{x}x_i = \bar{x}\sum_{i=1}^{n} x_i = \bar{x}(n\bar{x}) = n\bar{x}^2$

---

## 1. 分母的等價證明（方差變形）

我們從離差平方和 $\sum_{i=1}^{n} (x_i - \bar{x})^2$ 開始展開：

$$\sum_{i=1}^{n} (x_i - \bar{x})^2 = \sum_{i=1}^{n} (x_i^2 - 2x_i\bar{x} + \bar{x}^2)$$

將連加號 $\sum$ 分配進括號內的每一項：

$$= \sum_{i=1}^{n} x_i^2 - \sum_{i=1}^{n} 2x_i\bar{x} + \sum_{i=1}^{n} \bar{x}^2$$

將第二項的常數 $2\bar{x}$ 提至連加號前方，並應用性質 1 轉換第三項：

$$= \sum_{i=1}^{n} x_i^2 - 2\bar{x}\sum_{i=1}^{n} x_i + n\bar{x}^2$$

此時，根據性質 2，將第二項的 $\sum_{i=1}^{n} x_i$ 替換為 $n\bar{x}$：

$$= \sum_{i=1}^{n} x_i^2 - 2\bar{x}(n\bar{x}) + n\bar{x}^2$$
$$= \sum_{i=1}^{n} x_i^2 - 2n\bar{x}^2 + n\bar{x}^2$$

同類項合併後，即得證分母的恆等式：

$$\boxed{\sum_{i=1}^{n} (x_i - \bar{x})^2 = \sum_{i=1}^{n} x_i^2 - n\bar{x}^2}$$

---

## 2. 分子的等價證明（協方差變形）

我們同樣從離差交叉乘積和 $\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})$ 開始展開：

$$\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y}) = \sum_{i=1}^{n} (x_i y_i - x_i\bar{y} - \bar{x}y_i + \bar{x}\bar{y})$$

將連加號 $\sum$ 分配至每一項：

$$= \sum_{i=1}^{n} x_i y_i - \sum_{i=1}^{n} x_i\bar{y} - \sum_{i=1}^{n} \bar{x}y_i + \sum_{i=1}^{n} \bar{x}\bar{y}$$

將各項中的常數（$\bar{x}$ 或 $\bar{y}$）提出連加號外，並應用性質 1 轉換第四項：

$$= \sum_{i=1}^{n} x_i y_i - \bar{y}\sum_{i=1}^{n} x_i - \bar{x}\sum_{i=1}^{n} y_i + n\bar{x}\bar{y}$$

根據性質 2，我們知道 $\sum_{i=1}^{n} x_i = n\bar{x}$ 且 $\sum_{i=1}^{n} y_i = n\bar{y}$，將其代入第二項與第三項：

$$= \sum_{i=1}^{n} x_i y_i - \bar{y}(n\bar{x}) - \bar{x}(n\bar{y}) + n\bar{x}\bar{y}$$
$$= \sum_{i=1}^{n} x_i y_i - n\bar{x}\bar{y} - n\bar{x}\bar{y} + n\bar{x}\bar{y}$$

後方三項同類項相互抵消合併後，即得證分子的恆等式：

$$\boxed{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y}) = \sum_{i=1}^{n} x_i y_i - n\bar{x}\bar{y}}$$

---

## 💡 為什麼統計學更偏愛右邊的「離差形式」？

雖然左邊的原始公式在計算機運算時速度較快（只需要一筆筆累加 $x_i y_i$ 和 $x_i^2$），但右邊的離差形式在統計學上有三大無法取代的優勢：

1. **直觀的幾何與統計意義：**
   * 分子其實就是 $X$ 與 $Y$ 的**協方差（Covariance）**分子項，代表兩者同步變動的方向與強度。
   * 分母則是 $X$ 的**方差（Variance）**分子項（離差平方和），代表自變量的分散程度。
   * 因此，權重 $w$ 的本質就是：$\boxed{w = \frac{\text{Cov}(X,Y)}{\text{Var}(X)}}$。

2. **數值穩定性（防止浮點數溢位）：**
   * 當數據的絕對值非常大時（例如年份 $2026, 2027$ 或龐大的財政數據），直接計算 $x_i^2$ 會產生極大數字，導致電腦在計算浮點數時因**「大數減大數」**而產生嚴重的精度捨入誤差（Round-off error）。
   * 減去平均值後，數據會被「中心化」到 0 附近，數值會變小且穩定，極大地提高了程式計算的精確度。


# 線性迴歸求解
## 範例1. 簡單線性迴歸
### $\begin{equation}y = wx + b\end{equation}$

$$w = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}$$

$$b = \bar{y} - w\bar{x}$$

In [1]:
# 載入套件
from typing import cast

import numpy as np
import pandas as pd
import torch
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression

In [2]:
# 使用 OLS 公式計算 w、b
# 載入資料集
df = pd.read_csv('./data/population.csv')

w = ((df['year'] - df['year'].mean()) * (df['pop'] - df['pop'].mean())).sum() / ((df['year'] - df['year'].mean()) ** 2).sum()
b = df['pop'].mean() - w * df['year'].mean()

print(f'w={w}, b={b}')

w=0.061159358661554544, b=-116.35631056117114


In [3]:
# 使用 NumPy 的現成函數 polyfit()
coef = np.polyfit(df['year'], df['pop'], deg=1)
print(f'w={coef[0]}, b={coef[1]}')

w=0.061159358661554634, b=-116.3563105611713


## 矩陣計算

## 矩陣形式的最小平方法推導（Normal Equation）

在多變量（多元線性迴歸）的矩陣表示下，為了同時求解權重向量 $\mathbf{w}$ 與偏差 $b$，我們通常會使用一個數學技巧：**將偏差 $b$ 作為權重向量的第一個元素 $w_0$，並在特徵矩陣 $\mathbf{X}$ 的第一行（第一列）補上全為 1 的常數項**。

### 1. 矩陣與向量的定義

假設我們有 $n$ 筆樣本數據，每筆數據有 $d$ 個特徵。
*   **特徵矩陣 $\mathbf{X}$**（大小為 $n \times (d+1)$）：
    $$\mathbf{X} = \begin{bmatrix} 1 & x_{11} & x_{12} & \dots & x_{1d} \\ 1 & x_{21} & x_{22} & \dots & x_{2d} \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 1 & x_{n1} & x_{n2} & \dots & x_{nd} \end{bmatrix}$$
*   **真實標籤向量 $\mathbf{y}$**（大小為 $n \times 1$）：$\mathbf{y} = [y_1, y_2, \dots, y_n]^T$
*   **待求參數向量 $\mathbf{w}$**（大小為 $(d+1) \times 1$）：$\mathbf{w} = [b, w_1, w_2, \dots, w_d]^T$

此時，預測值向量 $\mathbf{\hat{y}}$ 即可簡寫為完美的矩陣乘法：
$$\mathbf{\hat{y}} = \mathbf{X}\mathbf{w}$$

---

### 2. 定義矩陣損失函數

最小平方法的優化目標是讓**殘差平方和（SSE）**降到最低。在矩陣中，向量的平方和可以用其自身與自身的**內積（轉置相乘）**來表示：

$$E(\mathbf{w}) = \|\mathbf{y} - \mathbf{\hat{y}}\|^2 = (\mathbf{y} - \mathbf{X}\mathbf{w})^T(\mathbf{y} - \mathbf{X}\mathbf{w})$$

我們將該式展開（注意矩陣乘法的分配律）：

$$E(\mathbf{w}) = (\mathbf{y}^T - \mathbf{w}^T\mathbf{X}^T)(\mathbf{y} - \mathbf{X}\mathbf{w})$$
$$E(\mathbf{w}) = \mathbf{y}^T\mathbf{y} - \mathbf{y}^T\mathbf{X}\mathbf{w} - \mathbf{w}^T\mathbf{X}^T\mathbf{y} + \mathbf{w}^T\mathbf{X}^T\mathbf{X}\mathbf{w}$$

> 💡 **數學小常識：** 因為 $\mathbf{y}^T\mathbf{X}\mathbf{w}$ 計算出來的結果是一個 **$1 \times 1$ 的純實數（純量）**，而純實數的轉置等於其自身：
> $$(\mathbf{y}^T\mathbf{X}\mathbf{w})^T = \mathbf{w}^T\mathbf{X}^T\mathbf{y}$$
> 
> 因此，中間兩項屬於同類項，可以合併。損失函數最終簡化為：

$$E(\mathbf{w}) = \mathbf{y}^T\mathbf{y} - 2\mathbf{w}^T\mathbf{X}^T\mathbf{y} + \mathbf{w}^T\mathbf{X}^T\mathbf{X}\mathbf{w}$$

---

### 3. 利用矩陣微積分求極值

為了找到使損失函數 $E(\mathbf{w})$ 最小的最佳參數，我們需要對向量 $\mathbf{w}$ 求偏導（偏微分），並令其等於零向量 $\mathbf{0}$。

這裡需要用到兩個核心的**矩陣微分公式**：
1. $\frac{\partial (\mathbf{w}^T\mathbf{a})}{\partial \mathbf{w}} = \mathbf{a}$
2. $\frac{\partial (\mathbf{w}^T\mathbf{A}\mathbf{w})}{\partial \mathbf{w}} = 2\mathbf{A}\mathbf{w}$ （其中 $\mathbf{A}$ 為對稱矩陣，此處的 $\mathbf{X}^T\mathbf{X}$ 即為對稱矩陣）

現在，我們對 $E(\mathbf{w})$ 進行求導：

$$\frac{\partial E}{\partial \mathbf{w}} = \frac{\partial (\mathbf{y}^T\mathbf{y})}{\partial \mathbf{w}} - \frac{\partial (2\mathbf{w}^T\mathbf{X}^T\mathbf{y})}{\partial \mathbf{w}} + \frac{\partial (\mathbf{w}^T\mathbf{X}^T\mathbf{X}\mathbf{w})}{\partial \mathbf{w}} = \mathbf{0}$$

*   第一項 $\mathbf{y}^T\mathbf{y}$ 中不含 $\mathbf{w}$，微分後為 $0$。
*   第二項應用公式 1，結果為 $-2\mathbf{X}^T\mathbf{y}$。
*   第三項應用公式 2，結果為 $2\mathbf{X}^T\mathbf{X}\mathbf{w}$。

帶入上式：

$$-2\mathbf{X}^T\mathbf{y} + 2\mathbf{X}^T\mathbf{X}\mathbf{w} = \mathbf{0}$$

---

### 4. 求解正規方程式（Normal Equation）

將上式移項並同除以 2：

$$\mathbf{X}^T\mathbf{X}\mathbf{w} = \mathbf{X}^T\mathbf{y}$$

假設矩陣 $\mathbf{X}^T\mathbf{X}$ 是**可逆矩陣（滿秩）**，我們可以在等式兩邊同時從左側乘以它的反矩陣（逆矩陣） $(\mathbf{X}^T\mathbf{X})^{-1}$：

$$(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{X}\mathbf{w} = (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}$$

因為 $(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{X} = \mathbf{I}$（單位矩陣），所以最終解得：

$$\boxed{\mathbf{w} = (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{y}}$$

這便是大名鼎鼎的**普通最小二乘法（OLS）矩陣閉式解公式**。


In [4]:
X = df[['year']].values

# b = b * 1
one = np.ones((len(df), 1))

# 將 x 與 one 合併
X = np.concatenate((X, one), axis=1)

y = df[['pop']].values

# 求解
w = np.linalg.inv(X.T @ X) @ X.T @ y
print(f'w={w[0, 0]}, b={w[1, 0]}')

w=0.06115935866154643, b=-116.35631056115506


## 以Scikit-Learn的房價資料集為例，求解線性迴歸

In [5]:
# 載入 Boston 房價資料集
X, y = cast(tuple[np.ndarray, np.ndarray], fetch_california_housing(return_X_y=True))

# b = b * 1
one = np.ones((X.shape[0], 1))

# 將 x 與 one 合併
X = np.concatenate((X, one), axis=1)

# 求解
w = np.linalg.inv(X.T @ X) @ X.T @ y
w

array([ 4.36693293e-01,  9.43577804e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638940e-06, -3.78654266e-03, -4.21314377e-01, -4.34513754e-01,
       -3.69419202e+01])

## 以Scikit-Learn的線性迴歸驗證

In [6]:
X, y = cast(tuple[np.ndarray, np.ndarray], fetch_california_housing(return_X_y=True))

lr = LinearRegression()
lr.fit(X, y)

lr.coef_, lr.intercept_

(array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
        -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01]),
 np.float64(-36.94192020718438))

## 使用PyTorch 線性代數函數庫

In [7]:
# 載入 Boston 房價資料集
X, y = cast(tuple[np.ndarray, np.ndarray], fetch_california_housing(return_X_y=True))

X_tensor = torch.from_numpy(X)

# b = b * 1
one = torch.ones((X.shape[0], 1))

# 將 x 與 one 合併
X = torch.cat((X_tensor, one), dim=1)


# 求解
w = torch.linalg.inv(X.T @ X) @ X.T @ y
# w = (X.T @ X).inverse() @ X.T @ y # 也可以

w

/var/folders/12/kxxl4khx6b9fjm12yv7z63y40000gn/T/ipykernel_20753/3753926301.py:14: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  w = torch.linalg.inv(X.T @ X) @ X.T @ y


tensor([ 4.3669e-01,  9.4358e-03, -1.0732e-01,  6.4507e-01, -3.9764e-06,
        -3.7865e-03, -4.2131e-01, -4.3451e-01, -3.6942e+01],
       dtype=torch.float64)