# 激勵函數(Activation Functions)

In [1]:
# 載入套件
import torch
from torch import nn

## ReLU

In [2]:
m = nn.ReLU()
input = torch.tensor([5, 2, 0, -10])
output = m(input)
output

tensor([5, 2, 0, 0])

## LeakyReLU

In [3]:
m = nn.LeakyReLU()
input = torch.tensor([5, 2, 0, -10, -100], dtype=torch.float)
output = m(input)
output

tensor([ 5.0000,  2.0000,  0.0000, -0.1000, -1.0000])

## Sigmoid

In [4]:
m = nn.Sigmoid()
input = torch.tensor([5, 2, 0, -10, -100], dtype=torch.float)
output = m(input)
output

tensor([9.9331e-01, 8.8080e-01, 5.0000e-01, 4.5398e-05, 0.0000e+00])

## Tanh

In [5]:
m = nn.Tanh()
input = torch.tensor([5, 2, 0, -10, -100], dtype=torch.float)
output = m(input)
output

tensor([ 0.9999,  0.9640,  0.0000, -1.0000, -1.0000])

## Softmax

In [6]:
m = nn.Softmax(dim=1)
input = torch.tensor([[1.0, 2.0, 3.0, 4.0]], dtype=torch.float)
output = m(input)
output

tensor([[0.0321, 0.0871, 0.2369, 0.6439]])

In [7]:
0.0321 + 0.0871 + 0.2369 + 0.6439

1.0